language: java
jdk:
- oraclejdk8
os:
- linux

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  
before_deploy:
- export RELEASE_PKG_FILE=$(ls build/libs/*.jar)
- echo "deploying $RELEASE_PKG_FILE to GitHub releases"

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: pfMQC5ypmdwDT1GKUIpWqRR/IHtCBCd/FBhenSwTMv81scu/x9HRBs1afsz0A6ubkeMYexLet47nnWST+fqn8VAWNN/JbuOwMyCZ4S0jdbFJXAHGTl1l5odM0xCeE27vmYB34ss79MrjZkvss3aNXAiTd4Bm72P2QpjzEUGYpsWaKD9nI9RoKFljTooAFLr3JYbzZXX9s1us9sZ8ussQiv93T5A+1lTtHH4ay2XDU1/35dKlBIegY1xh8D4nBxVqAmSdAMHIO+rtT5XzjeU6qNI0mMvowlfxTuZah5JJ01tS9Z3dJ9hMfeVUs/UKsbKtDWRBLaKUiES15XZ/AgV4FaXC332A7OrhnmX2y+gUTPdth3o/otqNB2W1tniTg++okoUZaXkZAndsDlO9ID+U7KlH9lnMLRTOxWmcoJLB7YRHaOTGJtcXIujrs+PtYNmFEFTvmdl4EUgNej02WCl2ly6L/wW0hdMGZdSUotM1tUTjIp7lBwGpj6cPIvfdrns4vYJndT7Ya5DhS7ShfUd7M2iYtGthFWKMFcc1EpM/L1F5xAXEiA87j00cQlsUXeLf0cw+AbI6nSFN4T6T2uTH6mQq7k2MR2fSA9g4L4hZXRna7ciCkQYs1mbloiZYYH8p+uXmDmB0NSBg76pl8v7EkMTW/B5pGQ/QLcgfni15P+s=
  file: "${RELEASE_PKG_FILE}"
  on:
    tags: true
    repo: antoine-aumjaud/api-javalib
    
notifications:
  email: 
    on_failure: always
    on_sucess: never
  webhooks:
    urls:
      - https://api-synology-chatbot.aumjaud.fr/secure/send-travis/travis-ci?secure-key=${CHAT_SECURE_KEY}
    on_success: always
    on_failure: always
