plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

dependencies {
    // Spark server
    implementation('com.sparkjava:spark-core:2.6.0') {
    	exclude group: 'org.slf4j' //old version
	}
    // Spring (context -> bean -> core)
	implementation('org.springframework.boot:spring-boot-starter-web:1.5.4.RELEASE') {
        exclude group: 'commons-logging' //useless with slf4j
    }

    // Common
    implementation 'org.slf4j:slf4j-api:1.7.25'
	implementation 'com.google.code.gson:gson:2.8.0'
	implementation 'org.bouncycastle:bcpkix-jdk15on:1.52'
	implementation 'com.auth0:java-jwt:3.3.0'

    // Tests
    testImplementation 'junit:junit:4.12'
    testRuntimeOnly 'ch.qos.logback:logback-classic:1.2.3'
}

tasks.named('jar') {
    archiveBaseName = 'api-javalib'
    archiveVersion = '1.14.1'
}
